"""Build PROGMEM C arrays from Fusion Pixel Font 12px monospaced BDFs.

Replaces the previous 16x16 HZK16-derived glyph tables with 12x12 ones so the
CJK build's HUD text fits more characters per row and leaves the GIF
character room to breathe. Two outputs:

- ``src/Fonts/ASC12.h``   — printable ASCII (0x20..0x7E), 6 wide × 12 tall,
  1 byte/row → 12 bytes per glyph. Indexed by byte value; non-printable
  slots are zeroed so a stray 0x00..0x1F never wanders into a wrong glyph.
- ``src/Fonts/GB2312_L1.h`` — GB2312 zones 1..55 (symbols + Level 1 hanzi),
  12 wide × 12 tall, 2 bytes/row → 24 bytes per glyph. Indexed by (zone,
  pos) via ``gb2312_l1_glyph``. Missing codepoints (Level 1 holes, some
  zone-1 reserved slots) get zero bytes — the caller's render routine
  detects an all-zero glyph by checking BBX or just blanks it out.

License compliance: Fusion Pixel Font ships under SIL Open Font License 1.1
(see src/Fonts/OFL.txt and src/Fonts/licenses/*.txt for source-specific
attributions). Generated bitmap arrays inherit OFL — we ship the license
file alongside the generated headers and add a notice at the top of each
output.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Optional

FONT_ROOT = Path("/tmp/fusion-pixel/extracted")
BDF_LATIN = FONT_ROOT / "fusion-pixel-12px-monospaced-latin.bdf"
BDF_ZH    = FONT_ROOT / "fusion-pixel-12px-monospaced-zh_hans.bdf"

OUT_DIR = Path("/Users/snow/claude-desktop-buddy/src/Fonts")
OUT_ASC = OUT_DIR / "ASC12.h"
OUT_GBK = OUT_DIR / "GB2312_L1.h"

# Glyph dimensions
GLYPH_H = 12
ASC_W = 6        # latin glyphs in this font happen to be 6 wide (mono per script)
GBK_W = 12
ASC_BYTES_PER_ROW = 1   # ceil(6/8)
GBK_BYTES_PER_ROW = 2   # ceil(12/8)
ASC_BYTES_PER_GLYPH = GLYPH_H * ASC_BYTES_PER_ROW   # 12
GBK_BYTES_PER_GLYPH = GLYPH_H * GBK_BYTES_PER_ROW   # 24

# GB2312 subset
ZONE_START = 1
ZONE_END = 56          # exclusive — zones 1..55
GLYPHS_PER_ZONE = 94
GBK_TOTAL_GLYPHS = (ZONE_END - ZONE_START) * GLYPHS_PER_ZONE


def parse_bdf(path: Path) -> dict[int, list[int]]:
    """Return {codepoint: glyph_bytes_flat_list}. Glyph bytes are the raw
    BITMAP rows decoded from hex, row-major, with each row padded to the
    nearest byte per BDF spec. Caller validates expected dimensions."""
    out: dict[int, list[int]] = {}
    text = path.read_text(encoding="utf-8")
    # Process character blocks.
    for block in re.split(r"^STARTCHAR ", text, flags=re.MULTILINE)[1:]:
        # block starts after "STARTCHAR ", everything up to ENDCHAR
        end = block.find("\nENDCHAR")
        if end < 0:
            continue
        body = block[:end]
        m = re.search(r"^ENCODING\s+(-?\d+)", body, re.MULTILINE)
        if not m:
            continue
        cp = int(m.group(1))
        if cp < 0:
            continue
        bitmap_match = re.search(r"^BITMAP\s*$", body, re.MULTILINE)
        if not bitmap_match:
            continue
        hex_rows = []
        for line in body[bitmap_match.end():].splitlines():
            line = line.strip()
            if not line:
                continue
            if not re.fullmatch(r"[0-9A-Fa-f]+", line):
                break
            hex_rows.append(line)
        # Each hex row → list of bytes
        glyph: list[int] = []
        for row in hex_rows:
            # row length must be even; pad odd (defensive)
            if len(row) % 2:
                row += "0"
            for i in range(0, len(row), 2):
                glyph.append(int(row[i:i + 2], 16))
        out[cp] = glyph
    return out


def gbk_to_unicode(zone: int, pos: int) -> Optional[str]:
    """Decode the GB2312 (zone, pos) cell to its Unicode codepoint, or None
    if the cell is unmapped/invalid."""
    if zone < 1 or zone > 94 or pos < 1 or pos > 94:
        return None
    raw = bytes([0xA0 + zone, 0xA0 + pos])
    try:
        decoded = raw.decode("gbk")
    except UnicodeDecodeError:
        return None
    if len(decoded) != 1:
        return None
    return decoded


def emit_header(name: str, var: str, glyphs: list[list[int]], bytes_per_glyph: int,
                glyph_w: int, glyph_h: int, bytes_per_row: int,
                lookup: Optional[str]) -> str:
    lines = [
        "/* Auto-generated by scripts/convert_fusion_pixel_12.py — do not edit. */",
        "/* Source: Fusion Pixel Font 12px monospaced (https://github.com/TakWolf/fusion-pixel-font). */",
        "/* Licensed under SIL Open Font License 1.1 — see Fonts/OFL.txt. */",
        "",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"#define {var}_GLYPH_W {glyph_w}",
        f"#define {var}_GLYPH_H {glyph_h}",
        f"#define {var}_BYTES_PER_ROW {bytes_per_row}",
        f"#define {var}_BYTES_PER_GLYPH {bytes_per_glyph}",
        f"#define {var}_GLYPH_COUNT {len(glyphs)}",
        "",
        f"const uint8_t {var}[{var}_GLYPH_COUNT * {var}_BYTES_PER_GLYPH] PROGMEM = {{",
    ]
    BYTES_PER_LINE = 12
    for g_idx, g in enumerate(glyphs):
        # Normalise length: pad short, truncate long.
        if len(g) < bytes_per_glyph:
            g = g + [0] * (bytes_per_glyph - len(g))
        elif len(g) > bytes_per_glyph:
            g = g[:bytes_per_glyph]
        row_bytes = ",".join(f"0x{b:02X}" for b in g)
        lines.append(f"    /* {g_idx} */ {row_bytes},")
    lines.append("};")
    lines.append("")
    if lookup:
        lines.append(lookup)
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not BDF_LATIN.exists() or not BDF_ZH.exists():
        print(f"BDF files missing — expected at {FONT_ROOT}", file=sys.stderr)
        return 1

    latin = parse_bdf(BDF_LATIN)
    zh    = parse_bdf(BDF_ZH)
    print(f"parsed latin: {len(latin)} glyphs, zh_hans: {len(zh)} glyphs")

    # --- ASCII (0..127) ---
    ascii_glyphs: list[list[int]] = []
    for c in range(128):
        g = latin.get(c)
        if g and len(g) >= ASC_BYTES_PER_GLYPH:
            ascii_glyphs.append(g[:ASC_BYTES_PER_GLYPH])
        else:
            ascii_glyphs.append([0] * ASC_BYTES_PER_GLYPH)
    OUT_ASC.write_text(emit_header(
        "ASC12", "ASC12", ascii_glyphs,
        ASC_BYTES_PER_GLYPH, ASC_W, GLYPH_H, ASC_BYTES_PER_ROW,
        lookup=None,
    ))
    print(f"wrote {OUT_ASC}: {len(ascii_glyphs)} glyphs × {ASC_BYTES_PER_GLYPH} B = "
          f"{len(ascii_glyphs)*ASC_BYTES_PER_GLYPH} B")

    # --- GB2312 zones 1..55 ---
    gb_glyphs: list[list[int]] = []
    hits = 0
    misses = 0
    for zone in range(ZONE_START, ZONE_END):
        for pos in range(1, GLYPHS_PER_ZONE + 1):
            uni = gbk_to_unicode(zone, pos)
            g: list[int] = []
            if uni is not None:
                cp = ord(uni)
                g = zh.get(cp) or latin.get(cp) or []
                if len(g) >= GBK_BYTES_PER_GLYPH:
                    g = g[:GBK_BYTES_PER_GLYPH]
                    hits += 1
                else:
                    g = []
            if not g:
                g = [0] * GBK_BYTES_PER_GLYPH
                misses += 1
            gb_glyphs.append(g)
    print(f"GB2312 lookup: hits={hits}, misses={misses}, total={len(gb_glyphs)}")

    lookup = (
        f"#define GB2312_L1_ZONE_START  {ZONE_START}\n"
        f"#define GB2312_L1_ZONE_END    {ZONE_END}  /* exclusive */\n"
        "\n"
        "/* Map a GBK byte pair to a 24-byte glyph pointer, or nullptr if outside\n"
        "   the shipped zone range. The caller checks (b1, b2) sanity. */\n"
        "static inline const uint8_t* gb2312_l1_glyph(uint8_t b1, uint8_t b2) {\n"
        "  uint8_t zone = b1 - 0xA0;        /* zone 1..94 */\n"
        "  uint8_t pos  = b2 - 0xA0;        /* position 1..94 */\n"
        "  if (zone < GB2312_L1_ZONE_START || zone >= GB2312_L1_ZONE_END) return nullptr;\n"
        "  if (pos < 1 || pos > 94) return nullptr;\n"
        "  uint32_t idx = (uint32_t)(zone - GB2312_L1_ZONE_START) * 94 + (pos - 1);\n"
        "  return GB2312_L1 + idx * GB2312_L1_BYTES_PER_GLYPH;\n"
        "}\n"
    )
    OUT_GBK.write_text(emit_header(
        "GB2312_L1", "GB2312_L1", gb_glyphs,
        GBK_BYTES_PER_GLYPH, GBK_W, GLYPH_H, GBK_BYTES_PER_ROW,
        lookup=lookup,
    ))
    print(f"wrote {OUT_GBK}: {len(gb_glyphs)} glyphs × {GBK_BYTES_PER_GLYPH} B = "
          f"{len(gb_glyphs)*GBK_BYTES_PER_GLYPH} B")
    return 0


if __name__ == "__main__":
    sys.exit(main())
