"""Extract a usable GB2312 subset from M5StickCPlus's HZK16.h.

The bundled HZK16 covers ~8363 glyphs over the full 94×94 GBK grid. We don't
want the whole thing (~270 KB) but we *do* need more than just Level 1
hanzi: most daily Chinese content has full-width punctuation (zone 1),
full-width ASCII (zone 3), kana (zones 4-5), and similar symbols that all
live in zones 1-9. Without those, '，' '。' '！' '？' '、' '…' all render
as the fallback '??'.

Shipped: zones 1-55 = symbols/punctuation (1-9) + reserved 10-15 (zero
glyphs, ~45 KB of zeros) + Level 1 hanzi (16-55). 55 × 94 × 32 ≈ 162 KB.

Naming kept as ``GB2312_L1`` for backward compat with the original commit;
the content scope is documented here.
"""

import re
import sys
from pathlib import Path

SRC = Path("/Users/snow/claude-desktop-buddy/.pio/libdeps/m5stickc-plus/M5StickCPlus/src/Fonts/HZK16.h")
DST = Path("/Users/snow/claude-desktop-buddy/src/Fonts/GB2312_L1.h")

# GB2312 zones 1-55: symbols + Level 1 hanzi (incl. zero-filled reserved 10-15).
ZONE_START = 1    # inclusive
ZONE_END   = 56   # exclusive  (zones 1..55)
BYTES_PER_GLYPH = 32
GLYPHS_PER_ZONE = 94

START_BYTE = (ZONE_START - 1) * GLYPHS_PER_ZONE * BYTES_PER_GLYPH
END_BYTE   = (ZONE_END   - 1) * GLYPHS_PER_ZONE * BYTES_PER_GLYPH
SLICE_BYTES = END_BYTE - START_BYTE
SLICE_GLYPHS = (ZONE_END - ZONE_START) * GLYPHS_PER_ZONE


def parse_bytes(src_text: str) -> list[int]:
    # Extract every `0xNN` literal in order, in one pass.
    return [int(m, 16) for m in re.findall(r"0x[0-9A-Fa-f]{2}", src_text)]


def emit_header(payload: list[int]) -> str:
    assert len(payload) == SLICE_BYTES, f"slice mismatch: {len(payload)} vs {SLICE_BYTES}"
    lines = [
        "/* Auto-generated by scripts/extract_gb2312_l1.py — do not edit by hand. */",
        "/* GB2312 Level 1 (zones 16-55, positions 1-94) = 3760 glyphs × 32 B = 120 KB. */",
        "",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"#define GB2312_L1_ZONE_START  {ZONE_START}",
        f"#define GB2312_L1_ZONE_END    {ZONE_END}  /* exclusive */",
        f"#define GB2312_L1_GLYPH_COUNT {SLICE_GLYPHS}",
        f"#define GB2312_L1_BYTES_PER_GLYPH {BYTES_PER_GLYPH}",
        "",
        f"const uint8_t GB2312_L1[GB2312_L1_GLYPH_COUNT * GB2312_L1_BYTES_PER_GLYPH] PROGMEM = {{",
    ]
    # 16 bytes per line, comma-separated.
    BYTES_PER_LINE = 16
    for i in range(0, len(payload), BYTES_PER_LINE):
        row = ",".join(f"0x{b:02X}" for b in payload[i:i + BYTES_PER_LINE])
        lines.append(f"    {row},")
    lines[-1] = lines[-1].rstrip(",") + ""  # ok to keep trailing comma; ESP32 compiler tolerates
    lines.append("};")
    lines.append("")
    lines.append("/* Map a GBK byte pair to a glyph pointer, or nullptr if out of Level 1 range.")
    lines.append("   Caller is responsible for the (b1 >= 0xA1, b2 >= 0xA1) sanity check; we only")
    lines.append("   check the zone range here. */")
    lines.append("static inline const uint8_t* gb2312_l1_glyph(uint8_t b1, uint8_t b2) {")
    lines.append("  uint8_t zone = b1 - 0xA0;        /* zone 1..94 */")
    lines.append("  uint8_t pos  = b2 - 0xA0;        /* position 1..94 */")
    lines.append("  if (zone < GB2312_L1_ZONE_START || zone >= GB2312_L1_ZONE_END) return nullptr;")
    lines.append("  if (pos < 1 || pos > 94) return nullptr;")
    lines.append("  uint32_t idx = (uint32_t)(zone - GB2312_L1_ZONE_START) * 94 + (pos - 1);")
    lines.append("  return GB2312_L1 + idx * GB2312_L1_BYTES_PER_GLYPH;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not SRC.exists():
        print(f"source not found: {SRC}", file=sys.stderr)
        return 1
    payload = parse_bytes(SRC.read_text())
    if len(payload) < END_BYTE:
        print(f"HZK16 only has {len(payload)} bytes; need at least {END_BYTE}", file=sys.stderr)
        return 1
    sliced = payload[START_BYTE:END_BYTE]
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text(emit_header(sliced))
    print(f"wrote {DST}: {len(sliced)} bytes covering {SLICE_GLYPHS} glyphs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
